# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pagez
email: ahnmo@pagez.kr
description: > # this means to ignore newlines until "baseurl:"
  LoL
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://blog.pagez.kr" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

gems: [jekyll-paginate]

paginate: 5
paginate_path: "/page/:num"


# Build settings
markdown: kramdown
