title:              Pagez
tagline:            'Computer Security Study Blog'
description:        >
  Pagez
url:                http://blog.pagez.kr

email:              ahnmo@pagez.kr

baseurl:            /

gems: [jekyll-paginate]
paginate:           5
paginate_path:      "/page/:num"
